name: CI

on:
  push:
    branches:
      - main
    tags:
      - v**
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GitHub_TOKEN }}
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 22.19.0
          cache: pnpm
      - run: pnpm install
      - run: pnpm lint:check

  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GitHub_TOKEN }}
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 22.19.0
          cache: pnpm
      - run: pnpm install
      - run: pnpm build

      - name: Upload build result
        uses: actions/upload-artifact@v4
        with:
          name: build-result
          path: |
            **/dist/
            !**/node_modules

  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    needs:
      - build
    env:
      GITHUB_TOKEN: ${{ secrets.GitHub_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.npm_token_zotero_plugin }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Restore Build Result
        uses: actions/download-artifact@v5
        with:
          name: build-result

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22.19.0
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - run: pnpm i

      - name: Publish to NPM and sync to GitHub
        if: github.event_name == 'push' && github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
        run: |
          pnpm publish --no-git-checks
          pnpx changelogithub
        env:
          NPM_CONFIG_PROVENANCE: true
